# Generated by Django 2.0.6 on 2019-03-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0002_auto_20190312_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiapp.PostModel'),
        ),
    ]
