# Generated by Django 2.0.6 on 2019-03-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiapp', '0008_auto_20190318_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='relatedmodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiapp.PostModel'),
        ),
    ]
